[package]
authors = ["Luke Hinds <lhinds@redhat.com>"]
edition = "2018"
name = "actix_keylime"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = {version = "1.0.117", features = ["derive"]}
